### ISSUE TITLE
Brand Assets Page

### ISSUE THREAD

**Issue by pimato** [fMercury/dxdao-landing-page#11]
With more and more products owned by the Dxdao it is important to have all brand assets in one place. Therefor, I am proposing to add a Brand Assets Page:

This page should be accessed through the footer of dxdao.eth:
<img width="1440" alt="brands" src="https://user-images.githubusercontent.com/5337809/83667335-7f8cc780-a5ce-11ea-92ff-a2d1a80b0812.png">

Figma:
[View](https://www.figma.com/proto/7splg18QAqjzr6XwSnXDMX/Landing?node-id=464%3A0&viewport=-7119%2C-1430%2C0.5181348323822021&scaling=min-zoom)
[Design specification](https://www.figma.com/file/7splg18QAqjzr6XwSnXDMX/Landing?node-id=464%3A0)

Dxdao Logo:
[dxdao-blue.zip](https://github.com/fMercury/dxdao-landing-page/files/4724879/dxdao-blue.zip)
[dxdao-dark.zip](https://github.com/fMercury/dxdao-landing-page/files/4724893/dxdao-dark.zip)

Omen logo:
[omen-blue.zip](https://github.com/fMercury/dxdao-landing-page/files/4724903/omen-blue.zip)
[omen-dark.zip](https://github.com/fMercury/dxdao-landing-page/files/4724910/omen-dark.zip)

Mix logo:
[mix-dark.zip](https://github.com/fMercury/dxdao-landing-page/files/4724923/mix-dark.zip)

Dxswap logo:
[dxswap-purple.zip](https://github.com/fMercury/dxdao-landing-page/files/4724937/dxswap-purple.zip)
[dxswap-black.zip](https://github.com/fMercury/dxdao-landing-page/files/4724947/dxswap-black.zip)

Mesa logo:
[mesa-black.zip](https://github.com/fMercury/dxdao-landing-page/files/4724987/mesa-black.zip)

**Comment by nicoelzer** [comment]
@pimato self-assignment seems to be deactivated – could you assign to me ?
