### ISSUE TITLE
logo media links do not work on ipfs link

### ISSUE THREAD

**Issue by pimato** [fMercury/dxdao-landing-page#24]
https://ipfs.io/ipfs/QmZhfn3zZB8MGgpGFDoMAxU5diRR2HKAswmgECRrzQ5YCp/#/brand-assets

Something is wrong with the links

**Comment by nicoelzer** [comment]
Adding a dot in the file path should do it:

`svg: '/brand/dxdao-blue.svg',`

`svg: './brand/dxdao-blue.svg',`
